export interface MnemonicIdGenerator {
  generate(exists: (candidate: string) => boolean): string
}

export type RandomIndex = (upperBound: number) => number

const subjects = [
  "badger",
  "bear",
  "beaver",
  "bison",
  "crane",
  "deer",
  "dolphin",
  "eagle",
  "falcon",
  "finch",
  "fox",
  "gecko",
  "heron",
  "ibis",
  "jaguar",
  "koala",
  "lemur",
  "lion",
  "lynx",
  "marten",
  "moose",
  "otter",
  "owl",
  "panda",
  "panther",
  "parrot",
  "puma",
  "rabbit",
  "raven",
  "seal",
  "sparrow",
  "tiger",
  "turtle",
  "walrus",
  "whale",
  "wolf",
  "wren",
  "yak",
  "zebra",
  "alpaca",
  "antelope",
  "buffalo",
  "camel",
  "cougar",
  "coyote",
  "gazelle",
  "gibbon",
  "gorilla",
  "hamster",
  "hedgehog",
  "horse",
  "kingfisher",
  "leopard",
  "magpie",
  "meerkat",
  "narwhal",
  "ocelot",
  "oriole",
  "penguin",
  "porpoise",
  "robin",
  "salmon",
  "swift",
  "toucan",
] as const

const verbs = [
  "builds",
  "carries",
  "charts",
  "chooses",
  "collects",
  "crosses",
  "discovers",
  "draws",
  "explores",
  "finds",
  "follows",
  "guards",
  "guides",
  "holds",
  "joins",
  "keeps",
  "maps",
  "meets",
  "moves",
  "opens",
  "paints",
  "plants",
  "reads",
  "repairs",
  "reaches",
  "seeks",
  "shapes",
  "shares",
  "solves",
  "studies",
  "tracks",
  "visits",
  "watches",
  "weaves",
  "writes",
  "arranges",
  "balances",
  "brings",
  "checks",
  "climbs",
  "connects",
  "crafts",
  "examines",
  "gathers",
  "greets",
  "helps",
  "learns",
  "lights",
  "marks",
  "measures",
  "navigates",
  "observes",
  "organizes",
  "prepares",
  "protects",
  "raises",
  "restores",
  "reveals",
  "selects",
  "signals",
  "supports",
  "traces",
  "travels",
  "unlocks",
] as const

const objects = [
  "anchor",
  "arch",
  "beacon",
  "bridge",
  "brook",
  "canyon",
  "castle",
  "cedar",
  "circle",
  "cloud",
  "coast",
  "comet",
  "compass",
  "coral",
  "delta",
  "dune",
  "field",
  "forest",
  "garden",
  "gate",
  "glade",
  "harbor",
  "hill",
  "island",
  "lake",
  "lantern",
  "map",
  "meadow",
  "moon",
  "mountain",
  "oak",
  "ocean",
  "orbit",
  "path",
  "peak",
  "pine",
  "planet",
  "pond",
  "reef",
  "river",
  "road",
  "shore",
  "signal",
  "spring",
  "star",
  "stone",
  "summit",
  "sun",
  "temple",
  "tower",
  "trail",
  "tree",
  "valley",
  "village",
  "waterfall",
  "wave",
  "willow",
  "wind",
  "wood",
  "bay",
  "cliff",
  "desert",
  "grove",
  "horizon",
] as const

function cryptoIndex(upperBound: number): number {
  const values = new Uint32Array(1)
  crypto.getRandomValues(values)
  return (values[0] ?? 0) % upperBound
}

export class WordTripletIdGenerator implements MnemonicIdGenerator {
  readonly #randomIndex: RandomIndex
  readonly #attempts: number

  constructor(options: { randomIndex?: RandomIndex; attempts?: number } = {}) {
    this.#randomIndex = options.randomIndex ?? cryptoIndex
    this.#attempts = options.attempts ?? 128
  }

  generate(exists: (candidate: string) => boolean): string {
    for (let attempt = 0; attempt < this.#attempts; attempt++) {
      const candidate = [
        subjects[this.#randomIndex(subjects.length)],
        verbs[this.#randomIndex(verbs.length)],
        objects[this.#randomIndex(objects.length)],
      ].join("-")
      if (!exists(candidate)) return candidate
    }
    throw new Error("无法生成不重复的助记 ID")
  }
}
