name: docs

on:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
      - uses: ./.github/actions/docs-build
